In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier,plot_tree
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [2]:
df = pd.read_csv("CSV_Data/diabetes.csv")
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [3]:
df.shape
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [4]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
X = df.drop(columns=["Outcome"])
y = df["Outcome"]

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=45)

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
lr = LogisticRegression()
lr.fit(X_train,y_train)
lrp = lr.predict(X_test)
print("Accuracy Score : ",accuracy_score(y_test,lrp))

Accuracy Score :  0.7337662337662337

In [9]:
n_features = X_train.shape[1]

w = np.zeros(n_features)
b = 0

learning_rate = 0.01
epochs = 5000

In [10]:
def sigmoid(z):
    return 1/(1 + np.exp(-z))

In [11]:
def compute_loss(y,y_pred):

    m = len(y)
    epsilon = 1e-15
    
    y_pred = np.clip(y_pred,epsilon,1-epsilon)
        
    loss = -(1/m)*np.sum(y*np.log(y_pred)+(1-y)*np.log(1-y_pred))
    
    return loss

In [12]:
def compute_gradient(X,y,y_pred):
    m = len(y)
    dw = (1/m) * np.dot(X.T,(y_pred-y))
    db = (1/m) * np.sum(y_pred-y)
    return dw,db

In [13]:
loss_history = []

for epoch in range(epochs):

    # Linear Equation
    z = np.dot(X_train, w) + b

    # Prediction
    y_pred = sigmoid(z)

    # Loss
    loss = compute_loss(y_train, y_pred)

    loss_history.append(loss)

    # Gradient
    dw, db = compute_gradient(X_train, y_train, y_pred)

    # Update
    w = w - learning_rate * dw
    b = b - learning_rate * db

    if epoch % 100 == 0:
        print(f"Epoch {epoch}  Loss = {loss:.4f}")

Epoch 0  Loss = 0.6931
Epoch 100  Loss = 0.5994
Epoch 200  Loss = 0.5533
Epoch 300  Loss = 0.5267
Epoch 400  Loss = 0.5097
Epoch 500  Loss = 0.4979
Epoch 600  Loss = 0.4894
Epoch 700  Loss = 0.4831
Epoch 800  Loss = 0.4782
Epoch 900  Loss = 0.4744
Epoch 1000  Loss = 0.4714
Epoch 1100  Loss = 0.4689
Epoch 1200  Loss = 0.4670
Epoch 1300  Loss = 0.4654
Epoch 1400  Loss = 0.4641
Epoch 1500  Loss = 0.4630
Epoch 1600  Loss = 0.4620
Epoch 1700  Loss = 0.4613
Epoch 1800  Loss = 0.4606
Epoch 1900  Loss = 0.4601
Epoch 2000  Loss = 0.4596
Epoch 2100  Loss = 0.4592
Epoch 2200  Loss = 0.4589
Epoch 2300  Loss = 0.4586
Epoch 2400  Loss = 0.4583
Epoch 2500  Loss = 0.4581
Epoch 2600  Loss = 0.4580
Epoch 2700  Loss = 0.4578
Epoch 2800  Loss = 0.4577
Epoch 2900  Loss = 0.4575
Epoch 3000  Loss = 0.4574
Epoch 3100  Loss = 0.4574
Epoch 3200  Loss = 0.4573
Epoch 3300  Loss = 0.4572
Epoch 3400  Loss = 0.4572
Epoch 3500  Loss = 0.4571
Epoch 3600  Loss = 0.4571
Epoch 3700  Loss = 0.4570
Epoch 3800  Loss = 0.4570
Epoch 3900  Loss = 0.4570
Epoch 4000  Loss = 0.4569
Epoch 4100  Loss = 0.4569
Epoch 4200  Loss = 0.4569
Epoch 4300  Loss = 0.4569
Epoch 4400  Loss = 0.4569
Epoch 4500  Loss = 0.4568
Epoch 4600  Loss = 0.4568
Epoch 4700  Loss = 0.4568
Epoch 4800  Loss = 0.4568
Epoch 4900  Loss = 0.4568

In [14]:
z_test = np.dot(X_test, w) + b

probability = sigmoid(z_test)

prediction = (probability >= 0.5).astype(int)
prediction

array([1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0])

In [15]:
accuracy = accuracy_score(y_test, prediction)

print("Accuracy :", accuracy)

Accuracy : 0.7337662337662337

In [16]:
dt = DecisionTreeClassifier(random_state=56)
dt.fit(X_train,y_train)
dtp = dt.predict(X_test)
print("Accuracy Score : ",accuracy_score(y_test,dtp))

Accuracy Score :  0.6818181818181818

In [17]:
rf = RandomForestClassifier(random_state=45,n_estimators=100,min_samples_leaf=1,min_samples_split=2)
rf.fit(X_train,y_train)
rfp = rf.predict(X_test)
print("Accuracy Score : ",accuracy_score(y_test,rfp))

Accuracy Score :  0.7272727272727273

In [18]:
gb = GradientBoostingClassifier(n_estimators=100,learning_rate=0.01,max_depth=5,random_state=54)
gb.fit(X_train,y_train)
gbp = gb.predict(X_test)
accuracy_score(y_test,gbp)

0.7792207792207793

In [29]:
xgb = XGBClassifier(objective="binary:logistic",
    n_estimators=100,
    learning_rate=0.01,
    max_depth=4,
    random_state=34)
xgb.fit(X_train,y_train)
xgbp = xgb.predict(X_test)
accuracy_score(y_test,xgbp)

0.7467532467532467